const actions = {
  GET_GAMES_SUCCESS: 'GET_GAMES_SUCCESS',
  GET_GAMES_FAILURE: 'GET_GAMES_FAILURE',
  SET_GAME_SUCCESS: 'SET_GAME_SUCCESS',
  SET_GAME_FAILURE: 'SET_GAME_FAILURE',
  GET_USER_SUCCESS: 'GET_USER_SUCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',
};

export default actions;
