const actions = {
  GET_GAMES_SUCCESS: 'GET_GAMES_SUCCESS',
  GET_GAMES_FAILURE: 'GET_GAMES_FAILURE',
  SET_GAME_SUCCESS: 'SET_GAME_SUCCESS',
  SET_GAME_FAILURE: 'SET_GAME_FAILURE',
};

export default actions;
